kristofvc_web_controller_home:
    path: /
    defaults: { _controller: kristofvc_web.controller.home.view }
    methods: ["GET"]

#kristofvc_web_controller_work:
#    path: /work
#    defaults: { _controller: kristofvc_web.controller.work.view }
#    methods: ["GET"]

kristofvc_contact_controller_contact:
    path: /contact
    defaults: { _controller: kristofvc_contact.controller.contact }
    methods: ["GET", "POST"]
