---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: kristofvc.dev
    timezone: Europe/Brussels
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - node
    - composer
    - capifony
    - phpcommon
    - mysql
